services:

  # =========================
  # AIRFLOW (Celery ready)
  # =========================
  airflow-webserver:
    user: "${AIRFLOW_UID:-50000}:0"
    build: ./services/airflow/
    container_name: airflow-webserver
    restart: always
    command: webserver
    ports:
      - "8080:8080"
    environment:
      - AIRFLOW__CORE__EXECUTOR=CeleryExecutor
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@airflow-db:5432/airflow
      - AIRFLOW__CELERY__BROKER_URL=redis://redis:6379/0
      - AIRFLOW__CELERY__RESULT_BACKEND=db+postgresql://airflow:airflow@airflow-db:5432/airflow
      - AIRFLOW_CONN_CLICKHOUSE_FINHOUSE=generic://admin:admin@clickhouse:9000
      - AIRFLOW_CONN_TRINO_FINHOUSE=trino://admin@trino:8080/hive
      - AIRFLOW_CONN_POSTGRES_FINHOUSE=postgresql://finhouse:finhouse@postgres:5432/finhouse

    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
    depends_on:
      - airflow-db
      - redis
    networks:
      - finhouse-network
    
  airflow-scheduler:
    user: "${AIRFLOW_UID:-50000}:0"

    build: ./services/airflow/
    container_name: airflow-scheduler
    command: scheduler
    depends_on:
      - airflow-webserver
    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
    networks:
      - finhouse-network
    environment:
      - AIRFLOW__CORE__EXECUTOR=CeleryExecutor
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@airflow-db:5432/airflow
      - AIRFLOW__CELERY__BROKER_URL=redis://redis:6379/0
      - AIRFLOW__CELERY__RESULT_BACKEND=db+postgresql://airflow:airflow@airflow-db:5432/airflow
      - AIRFLOW_CONN_CLICKHOUSE_FINHOUSE=generic://admin:admin@clickhouse:9000
      - AIRFLOW_CONN_TRINO_FINHOUSE=trino://admin@trino:8080/hive
      - AIRFLOW_CONN_POSTGRES_FINHOUSE=postgresql://finhouse:finhouse@postgres:5432/finhouse

  airflow-worker:
    build: ./services/airflow/
    command: celery worker
    deploy:
      replicas: 2
    depends_on:
      - airflow-webserver
    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
      - /var/run/docker.sock:/var/run/docker.sock

    networks:
      - finhouse-network
    environment:
      - AIRFLOW__CORE__EXECUTOR=CeleryExecutor
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@airflow-db:5432/airflow
      - AIRFLOW__CELERY__BROKER_URL=redis://redis:6379/0
      - AIRFLOW__CELERY__RESULT_BACKEND=db+postgresql://airflow:airflow@airflow-db:5432/airflow

      - AIRFLOW_CONN_CLICKHOUSE_FINHOUSE=generic://admin:admin@clickhouse:9000
      - AIRFLOW_CONN_TRINO_FINHOUSE=trino://admin@trino:8080/hive
      - AIRFLOW_CONN_POSTGRES_FINHOUSE=postgresql://finhouse:finhouse@postgres:5432/finhouse

  airflow-flower:
    build: ./services/airflow/
    container_name: airflow-flower
    command: celery flower
    ports:
      - "5555:5555"
    depends_on:
      - airflow-webserver
    networks:
      - finhouse-network

  airflow-db:
    image: postgres:15
    container_name: airflow_db
    environment:
      POSTGRES_DB: airflow
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
    volumes:
      - airflow_db_data:/var/lib/postgresql/data
    networks:
      - finhouse-network

  redis:
    image: redis:7
    container_name: redis
    networks:
      - finhouse-network
  airflow-init:
    build: ./services/airflow/
    container_name: airflow-init
    depends_on:
      - airflow-db
      - redis
    environment:
      - AIRFLOW__CORE__EXECUTOR=CeleryExecutor
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@airflow-db:5432/airflow
      - AIRFLOW__CELERY__BROKER_URL=redis://redis:6379/0
      - AIRFLOW__CELERY__RESULT_BACKEND=db+postgresql://airflow:airflow@airflow-db:5432/airflow
      - AIRFLOW_CONN_CLICKHOUSE_FINHOUSE=generic://finhouse:finhouse@clickhouse:9000
      - AIRFLOW_CONN_TRINO_FINHOUSE=trino://admin@trino:8080/hive
      - AIRFLOW_CONN_POSTGRES_FINHOUSE=postgresql://finhouse:finhouse@postgres:5432/finhouse
    entrypoint: /bin/bash
    command: >
      -c "
      airflow db migrate &&
      airflow users create \
      --username admin \
      --password admin \
      --firstname admin \
      --lastname admin \
      --role Admin \
      --email admin@example.com
      "
    restart: "no"
    networks:
    - finhouse-network
  # =========================
  # KAFKA (KRaft)
  # =========================
  kafka:
    image: apache/kafka:3.7.0
    container_name: kafka
    ports:
    - "9092:9092"

    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
    volumes:
      - kafka_data:/var/lib/kafka/data

    networks:
      - finhouse-network

  schema-registry:
    image: confluentinc/cp-schema-registry:7.5.0
    container_name: schema-registry
    ports:
      - "8085:8081"
    environment:
      SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS: PLAINTEXT://kafka:9092
    depends_on:
      - kafka
    networks:
      - finhouse-network

  kafka-ui:
    image: provectuslabs/kafka-ui
    container_name: kafka-ui
    ports:
      - "8086:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9092
    depends_on:
      - kafka
    networks:
      - finhouse-network
  consumer:
    build: ./services/kafka/consumer
    container_name: consumer
    
    restart: always
    depends_on:
      clickhouse:
        condition: service_healthy
      kafka:
        condition: service_started
    networks:
    - finhouse-network
  
    # =========================
  # DATA STACK
  # =========================

  minio:
    image: minio/minio
  
    container_name: minio
    command: server /data --console-address ":9001"
    ports:
      - "9002:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: supersecretpassword
    volumes:
      - minio_data:/data
      - ./services/trino/catalog:/etc/trino/catalog

    networks:
      - finhouse-network
  minio-init:
    image: minio/minio
    container_name: minio_setup
    depends_on:
      - minio
    volumes:
      # Ánh xạ file entrypoint.sh từ máy tính vào bên trong container
      - ./services/minio/entrypoint.sh:/entrypoint.sh

    # Chạy file sh vừa được đưa vào
    entrypoint: ["/bin/sh", "/entrypoint.sh"]
    networks:
      - finhouse-network
    restart: "no"

  postgres-metastore:
    image: postgres:15
    container_name: postgres-metastore
    environment:
      POSTGRES_USER: hive
      POSTGRES_PASSWORD: hive123
      POSTGRES_DB: metastore
    ports:
      - "5433:5432"
    networks:
      - finhouse-network
  hive-metastore:
    build: ./services/hive
    container_name: hive-metastore
    depends_on:
      - postgres-metastore
    volumes:
      - ./services/hive/site.xml:/opt/hive/conf/hive-site.xml
    environment:
      SERVICE_NAME: metastore
      DB_DRIVER: postgres
      SERVICE_OPTS: >
        -Djavax.jdo.option.ConnectionURL=jdbc:postgresql://postgres-metastore:5432/metastore
        -Djavax.jdo.option.ConnectionDriverName=org.postgresql.Driver
        -Djavax.jdo.option.ConnectionUserName=hive
        -Djavax.jdo.option.ConnectionPassword=hive123
      AWS_ACCESS_KEY_ID: admin
      AWS_SECRET_ACCESS_KEY: supersecretpassword
      AWS_REGION: us-east-1
    ports:
      - "9083:9083"
    networks:
      - finhouse-network
  trino:
    image: trinodb/trino:475
    container_name: trino
    ports:
      - "8000:8080"
    volumes:
      - ./services/trino/catalog:/etc/trino/catalog
      - ./services/trino/init_db.sql:/docker-init/init_db.sql
      - ./services/trino/entrypoint.sh:/docker-init/entrypoint.sh
    entrypoint: [ "/bin/sh", "/docker-init/entrypoint.sh" ]
    depends_on:
      - hive-metastore
    networks:
      - finhouse-network
  # =========================
  # MONITORING
  # =========================
  grafana:
    image: grafana/grafana:10.2.0
    container_name: grafana
    ports:
      - "3001:3000"
    volumes:
      - grafana_data:/var/lib/grafana
    networks:
      - finhouse-network

  prometheus:
    image: prom/prometheus:v2.45.0
    container_name: prometheus
    volumes:
      - prometheus_data:/prometheus
    ports:
      - "9090:9090"
    networks:
      - finhouse-network

  # =========================
  # BI
  # =========================
  superset:
    build: ./services/superset
    container_name: superset
    ports:
      - "8088:8088"
    environment:
      SUPERSET_SECRET_KEY: supersecretkey
      SUPERSET_DATABASE_URI: postgresql+psycopg2://superset:superset@superset-db:5432/superset

    depends_on:
      - trino
      - superset-db
    volumes:
      - superset_home:/app/superset_home
    networks:
      - finhouse-network
  superset-db:
    image: postgres:15 

    container_name: superset-db

    environment:
      POSTGRES_DB: superset
      POSTGRES_USER: superset
      POSTGRES_PASSWORD: superset

    volumes:
      - superset_db:/var/lib/postgresql/data

    networks:
      - finhouse-network
  # =========================
  # POSTGRES
  # =========================
  postgres:
    image: postgres:15
    container_name: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: finhouse
      POSTGRES_USER: finhouse
      POSTGRES_PASSWORD: finhouse
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./services/postgres/init_db.sql:/docker-entrypoint-initdb.d/init_db.sql
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "finhouse", "-d", "finhouse"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - finhouse-network

  # =========================
  # CLICKHOUSE
  # =========================
  clickhouse:
    image: clickhouse/clickhouse-server:24.3
    container_name: clickhouse
    restart: always
    ports:
      - "8123:8123"   # HTTP
      - "9000:9000"   # Native client
    environment:
      CLICKHOUSE_DB: finhouse
      CLICKHOUSE_USER: admin
      CLICKHOUSE_PASSWORD: admin
    volumes:
      - clickhouse_data:/var/lib/clickhouse
      - ./services/clickhouse/init_db.sql:/docker-entrypoint-initdb.d/init_db.sql
      - ./services/clickhouse/config.xml:/etc/clickhouse-server/config.d/config.xml
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    networks:
      - finhouse-network
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "localhost:8123/ping"]
      interval: 10s
      timeout: 5s
      retries: 5
  spark-master:
    image: apache/spark:4.2.0-preview5-scala2.13-java17-python3-ubuntu
    container_name: spark-master
    hostname: spark-master
    command: >
      /opt/spark/bin/spark-class
      org.apache.spark.deploy.master.Master
    volumes:
      - ./services/spark/jobs:/opt/spark/jobs
    ports:
      - "8082:8080"
      - "7077:7077"
    networks:
      - finhouse-network

  spark-worker:
    image: apache/spark:4.2.0-preview5-scala2.13-java17-python3-ubuntu
    container_name: spark-worker
    hostname: spark-worker
    command: >
      /opt/spark/bin/spark-class
      org.apache.spark.deploy.worker.Worker
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
    depends_on:
      - spark-master
    networks:
      - finhouse-network
# ===================== VOLUMES =====================
volumes:
  airflow_db_data:
  kafka_data:
  metabase_db_data:
  grafana_data:
  prometheus_data:
  minio_data:
  postgres_data:
  clickhouse_data:
  superset_home:
  superset_db:
# ===================== NETWORK =====================
networks:
  finhouse-network:
    driver: bridge